# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1478768255);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1478768375);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1478829596);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1478768135);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1478767924);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1478768495);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1478767688);
user_pref("browser.laterrun.bookkeeping.sessionCount", 8);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 38);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1478829490095");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1478831359095");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1478829491497");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1478833091497");
user_pref("browser.search.countryCode", "VN");
user_pref("browser.search.region", "VN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20161025170711");
user_pref("browser.slowStartup.averageTime", 3606);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20161025170711");
user_pref("browser.startup.homepage_override.mstone", "49.0.2");
user_pref("browser.startup.page", 0);
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.daysBeforeHidingSuggestionsPrompt", 2);
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20161111);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1478767749238");
user_pref("datareporting.sessions.current.activeTicks", 11);
user_pref("datareporting.sessions.current.firstPaint", 5515);
user_pref("datareporting.sessions.current.main", 1571);
user_pref("datareporting.sessions.current.sessionRestored", 5755);
user_pref("datareporting.sessions.current.startTime", "1478829472757");
user_pref("datareporting.sessions.current.totalTime", 324);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.0", "{\"s\":1478767680831,\"a\":13,\"t\":309,\"c\":true,\"m\":1211,\"fp\":9115,\"sr\":8347}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1478768014692,\"a\":73,\"t\":697,\"c\":false,\"m\":21,\"fp\":3625,\"sr\":3441}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1478769500702,\"a\":2,\"t\":12,\"c\":true,\"m\":50,\"fp\":6741,\"sr\":5867}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1478769656363,\"a\":6,\"t\":42,\"c\":true,\"m\":51,\"fp\":3249,\"sr\":3026}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1478769708115,\"a\":1,\"t\":5,\"c\":true,\"m\":41,\"fp\":2221,\"sr\":2272}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1478769715167,\"a\":27,\"t\":197,\"c\":true,\"m\":31,\"fp\":2264,\"sr\":2377}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1478770069844,\"a\":40,\"t\":509,\"c\":true,\"m\":42,\"fp\":3593,\"sr\":3704}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.lastUpdate.buildID", "20161025170711");
user_pref("dom.apps.lastUpdate.mstone", "49.0.2");
user_pref("dom.apps.reset-permissions", true);
user_pref("e10s.rollout.cohort", "disqualified-test");
user_pref("e10s.rollout.cohortSample", "0.365974");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"asyncrendering@mozilla.org\":{\"version\":\"2.0\",\"type\":\"extension\",\"descriptor\":\"/home/vagrant/.mozilla/firefox/69pjfhxz.default/features/{992c4764-dc9e-423c-9845-927b84ab8cb3}/asyncrendering@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"webcompat@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"firefox@getpocket.com\":{\"version\":\"1.0.4\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"e10srollout@mozilla.org\":{\"version\":\"1.3\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "49a");
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:49.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1478768258);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160826.01");
user_pref("extensions.lastAppVersion", "49.0.2");
user_pref("extensions.lastPlatformVersion", "49.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{992c4764-dc9e-423c-9845-927b84ab8cb3}\",\"addons\":{\"asyncrendering@mozilla.org\":{\"version\":\"2.0\"}}}");
user_pref("extensions.xpiState", "{\"app-system-addons\":{\"asyncrendering@mozilla.org\":{\"d\":\"/home/vagrant/.mozilla/firefox/69pjfhxz.default/features/{992c4764-dc9e-423c-9845-927b84ab8cb3}/asyncrendering@mozilla.org.xpi\",\"e\":true,\"v\":\"2.0\",\"st\":1478768266000}},\"app-system-defaults\":{\"webcompat@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1477418836000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.4\",\"st\":1477418836000},\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.3\",\"st\":1477418836000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"49.0.2\",\"st\":1477418836000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597112000}}}");
user_pref("idle.lastDailyNotification", 1478829968);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1478767752);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20161025170711");
user_pref("media.gmp-manager.lastCheck", 1478767750);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 52519);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1478829474);
user_pref("toolkit.telemetry.cachedClientID", "7d036fe0-cd6e-4330-a8af-caa51ec38804");
user_pref("toolkit.telemetry.previousBuildID", "20161025170711");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
