# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1478850178);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1478850298);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1479094049);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1478850058);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1478849938);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1478850418);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1478845353);
user_pref("browser.laterrun.bookkeeping.sessionCount", 7);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 38);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1479093946141");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1479095806141");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1479093947600");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1479097547600");
user_pref("browser.search.countryCode", "VN");
user_pref("browser.search.region", "VN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20161025170457");
user_pref("browser.slowStartup.averageTime", 4372);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20161025170457");
user_pref("browser.startup.homepage_override.mstone", "49.0.2");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.daysBeforeHidingSuggestionsPrompt", 3);
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20161114);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1478845942143");
user_pref("datareporting.sessions.current.activeTicks", 7);
user_pref("datareporting.sessions.current.firstPaint", 2427);
user_pref("datareporting.sessions.current.main", 31);
user_pref("datareporting.sessions.current.sessionRestored", 4723);
user_pref("datareporting.sessions.current.startTime", "1479103927274");
user_pref("datareporting.sessions.current.totalTime", 32);
user_pref("datareporting.sessions.currentIndex", 6);
user_pref("datareporting.sessions.previous.0", "{\"s\":1478845346442,\"a\":4,\"t\":36,\"c\":false,\"m\":1490,\"fp\":8896,\"sr\":8020}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1478845923133,\"a\":4,\"t\":36,\"c\":false,\"m\":1670,\"fp\":9566,\"sr\":8929}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1478849695937,\"a\":26,\"t\":761,\"c\":true,\"m\":791,\"fp\":5917,\"sr\":5643}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1478851345446,\"a\":1,\"t\":19,\"c\":false,\"m\":1071,\"fp\":9883,\"sr\":8864}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1479093925280,\"a\":24,\"t\":184,\"c\":true,\"m\":1441,\"fp\":8316,\"sr\":8021}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1479103683496,\"a\":1,\"t\":27,\"c\":false,\"m\":1331,\"fp\":7286,\"sr\":7636}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.lastUpdate.buildID", "20161025170457");
user_pref("dom.apps.lastUpdate.mstone", "49.0.2");
user_pref("dom.apps.reset-permissions", true);
user_pref("e10s.rollout.cohort", "disqualified-test");
user_pref("e10s.rollout.cohortSample", "0.569923");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"asyncrendering@mozilla.org\":{\"version\":\"2.0\",\"type\":\"extension\",\"descriptor\":\"/home/vagrant/.mozilla/firefox/gt3l307z.default/features/{650010fd-98c9-4614-a5ae-27d7cc780776}/asyncrendering@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"e10srollout@mozilla.org\":{\"version\":\"1.3\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"webcompat@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"firefox@getpocket.com\":{\"version\":\"1.0.4\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "49a");
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:49.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1478850179);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160826.01");
user_pref("extensions.lastAppVersion", "49.0.2");
user_pref("extensions.lastPlatformVersion", "49.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{650010fd-98c9-4614-a5ae-27d7cc780776}\",\"addons\":{\"asyncrendering@mozilla.org\":{\"version\":\"2.0\"}}}");
user_pref("extensions.xpiState", "{\"app-system-addons\":{\"asyncrendering@mozilla.org\":{\"d\":\"/home/vagrant/.mozilla/firefox/gt3l307z.default/features/{650010fd-98c9-4614-a5ae-27d7cc780776}/asyncrendering@mozilla.org.xpi\",\"e\":true,\"v\":\"2.0\",\"st\":1478850187000}},\"app-system-defaults\":{\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.3\",\"st\":1477424315000},\"webcompat@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1477424316000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.4\",\"st\":1477424316000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"49.0.2\",\"st\":1477424315000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597111000}}}");
user_pref("idle.lastDailyNotification", 1478849930);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1478849762);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20161025170457");
user_pref("media.gmp-manager.lastCheck", 1479093994);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1478849930);
user_pref("places.history.expiration.transient_current_max_pages", 52477);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1478849930);
user_pref("toolkit.startup.last_success", 1479103927);
user_pref("toolkit.telemetry.cachedClientID", "51c68926-18c9-4a7d-b057-28f3e50aa04e");
user_pref("toolkit.telemetry.previousBuildID", "20161025170457");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
